# Temporary GitPage Host setup
title: CS230 Deep Learning
baseurl: "/cs230-2020-fall"
repository: "cs230-stanford/website-fall-2020"

# Theme settings
doks:
    color_theme: blue
    header:
        logo:
            text: CS230
            image: true
        nav:
            - item_name: Syllabus
              item_url: '/syllabus'
            - item_name: Office Hours
              item_url: '/officehours'
            - item_name: Project
              item_url: '/project'
            - item_name: Section
              item_url: '/section'
            - item_name: Lecture
              item_url: '/lecture'
            - item_name: Blog
              item_url: '/blog'
            - item_name: FAQ
              item_url: '/faq'
    footer:
        content:
            logo:
                text:
                image:
            copyright: Copyright &copy; 2020. - Stanford University <br>All rights reserved.
        social_list:
            # - network_name: facebook
            #   profile_url: '#'
            # - network_name: twitter
            #   profile_url: '#'
    google_analytics: UA-124237072-3
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
plugins_dir: ./_plugins
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md', 'scripts']
permalink: /:title/

# Course logistics
course:
    quarter: 2020 Fall
    time: Tue 8:30 AM - 9:50 AM
    venue: '<a href="https://canvas.stanford.edu/courses/125215/external_tools/5384">Zoom (access via "Zoom" tab of Canvas)</a>'
    piazza: &pz 'https://piazza.com/class/kf0h64h1gem56g'
    queuestatus:
        url: &qs 'https://queuestatus.com/queues/1147'
        name: 'CS230 (2020 Fall)'
    nooks: &nks 'https://nooks.in/goto/ljci8fhSmAETzkzT?pwd=i9l0tQ'
    canvas: 'https://canvas.stanford.edu'
    midterm_time: ''
    project_timeline:
        proposal: 2020-09-30T23:59:00-07:00
        milestone: 2020-10-30T23:59:00-07:00
        poster_and_report: 2020-11-17T9:50:00-07:00
        long_date_format: "%B %-d, %A %I:%M %p"
        syllabus_date_format: "%m/%d %A %I:%M %p"
    links:
        syllabus:
            icon:
            content: Syllabus
            url: '/syllabus'
            external_url: false
        past-projects:
            icon:
            content: Past Projects
            url: '/past-projects'
            external_url: false
        project-2018-win:
            icon:
            content: Winter 2018
            url: '/past-projects/#winter-2018'
            external_url: false
        project-2018-spr:
            icon:
            content: Spring 2018
            url: '/past-projects/#spring-2018'
            external_url: false
        project-2018-fall:
            icon:
            content: Fall 2018
            url: '/past-projects/#fall-2018'
            external_url: false
        project-2019-win:
            icon:
            content: Winter 2019
            url: '/past-projects/#winter-2019'
            external_url: false
        project-2019-spr:
            icon:
            content: Spring 2019
            url: '/past-projects/#spring-2019'
            external_url: false
        project-2019-fall:
            icon:
            content: Fall 2019
            url: '/past-projects/#fall-2019'
            external_url: false
        project-2020-win:
            icon:
            content: Winter 2020
            url: '/past-projects/#winter-2020'
            external_url: false
        video2018:
            icon:
            content: Lecture videos (Fall 2018)
            url: '/lecture/'
            external_url: false
        piazza:
            icon:
            content: Piazza
            url: *pz
            external_url: true
        video:
            icon:
            content: Lecture videos (Canvas)
            url: 'https://canvas.stanford.edu/courses/125215/external_tools/5384'
            external_url: true
        nooks:
            icon:
            content: Nooks
            url: *nks
            external_url: true
        queuestatus:
            icon:
            content: QueueStatus
            url: *qs
            external_url: true
        project_appt_calendly:
            content: Meet with Project TA
            url: '/officehours/#table'
            external_url: true
    staff:
        - name: Andrew Ng
          type: Instructor
          url: https://www.andrewng.org/
          image: andrew.jpg
        - name: Kian Katanforoosh
          type: Instructor
          url: https://www.linkedin.com/in/kiankatan/
          image: kian.jpg
        - name: Swati Dube
          type: Coordinator
          url: http://www.linkedin.com/in/swatidube/
          image: swati.jpg
        - name: Amelie Byun
          type: Coordinator
          url: https://www.linkedin.com/in/aebyun/
          image: amelie.jpg
        - name: Shahab Mousavi
          type: Head TA
          url: https://www.linkedin.com/in/shahab-mousavi-39394738/
          image: shahab.jpg
          zoom_id: 9392472642
          zoom_link: https://stanford.zoom.us/my/ssmousav?pwd=azdXY1lQeTVTQ3hObG5PR2FyVENZdz09
          calendly: https://calendly.com/cs230fall2020/shahab-project-oh
    ta:
        - name: Jo Chuang
          type: TA
          url: https://jochuang.com/
          image: jo.jpg
          zoom_id: 8543765436
          zoom_link: https://stanford.zoom.us/j/8543765436
          calendly: https://calendly.com/cs230fall2020/jo-project-oh
        - name: Advay Pal
          type: TA
          url: https://advaypal.com/
          image: advay.jpg
          zoom_id: 5123418143
          zoom_link: https://stanford.zoom.us/my/advaypal?pwd=QmVwTUh4MnNoWkdVZlhtYjNGeUVSUT09
          calendly: https://calendly.com/cs230fall2020/advay-project-oh
        - name: Jonathan Lingjie Li
          type: TA
          url: https://www.linkedin.com/in/jonathan-li-23024679/
          image: jonathan.png
          zoom_id: 5824914282
          zoom_link: https://stanford.zoom.us/j/5824914282?pwd=RmNreGc0bFpSRFVRUXU2VjlnTzM2dz09
          calendly: https://calendly.com/cs230fall2020/jonathan-project-oh
        - name: Sharon Zhou
          type: TA
          url: https://sharonzhou.me/
          image: sharon.png
          zoom_id: 9332820016
          zoom_link: https://stanford.zoom.us/j/9332820016
          calendly: https://calendly.com/cs230fall2020/sharon-project-oh
        - name: Divyansh Garg
          type: TA
          url: https://divyanshgarg.com/
          image: div.jpg
          zoom_id: 4433698960
          zoom_link: https://stanford.zoom.us/j/4433698960?pwd=V0hseTloMzBtRmpValRBZWRpWm02dz09
          calendly: https://calendly.com/cs230fall2020/div-project-oh
        - name: Avoy Datta
          type: TA
          url: https://www.linkedin.com/in/avoy-datta/
          image: avoy.jpg
          zoom_id: 3287819697
          zoom_link: https://stanford.zoom.us/my/avoydatta?pwd=a0ZHV2hXZllwcTh4WFYvSWRoVFBpQT09
          calendly: https://calendly.com/cs230fall2020/avoy-project-oh
        - name: Tanay Kothari
          type: TA
          url: https://www.linkedin.com/in/tankots/
          image: tanay.png
          zoom_id: 4065573304
          zoom_link: https://stanford.zoom.us/j/4065573304?pwd=UFJkVjNTR1ArREVCWmhNcGMvMTc5dz09
          calendly: https://calendly.com/cs230fall2020/tanay-project-oh
